/* ════════════════════════════════════════════════════════════════
   LE DATE DI ANTRA — concerti, letture, spettacoli
   Generato con editor.html. Puoi anche modificarlo a mano.
   Campi: titolo, data ("AAAA-MM-GG"), ora, luogo,
          tipo (sushi|lydian|teatro|acustico|festa|concerto),
          locandina (file in images/live/locandine/), nota.
   ════════════════════════════════════════════════════════════════ */

window.MG_DATE = [

  { titolo:    "Vita da cantautrice",
    data:      "2026-05-20",
    ora:       "",
    luogo:     "",
    tipo:      "teatro",
    locandina: "",
    nota:      "" },

  { titolo:    "Festa privata al Curò",
    data:      "2026-05-30",
    ora:       "",
    luogo:     "Rifugio Antonio Curò, Valbondione (BG)",
    tipo:      "festa",
    locandina: "",
    nota:      "" },

  { titolo:    "Sushi Cornucopia",
    data:      "2026-06-06",
    ora:       "",
    luogo:     "Ardesio (BG)",
    tipo:      "sushi",
    locandina: "sushi.jpg",
    nota:      "" },

  { titolo:    "'Là, dove nasce l'acqua'",
    data:      "2026-06-21",
    ora:       "",
    luogo:     "Villa d'Ogna (BG)",
    tipo:      "teatro",
    locandina: "acqua.webp",
    nota:      "" },

  { titolo:    "'Al primo accordo' Simone Trevisan & Ghila",
    data:      "2026-07-04",
    ora:       "",
    luogo:     "Cerete (BG)",
    tipo:      "acustico",
    locandina: "trevisan.jpg",
    nota:      "" },

  { titolo:    "'Orizzonti acustici' Giorgio & Ghila",
    data:      "2026-07-11",
    ora:       "16:00",
    luogo:     "Valgoglio (BG)",
    tipo:      "acustico",
    locandina: "orizzonti.webp",
    nota:      "" },

  { titolo:    "'Là, dove nasce l'acqua'",
    data:      "2026-07-12",
    ora:       "16:00",
    luogo:     "Oltressenda Alta (BG)",
    tipo:      "teatro",
    locandina: "acqua.webp",
    nota:      "" },

  { titolo:    "Presentatore Concerto bandistico",
    data:      "2026-07-18",
    ora:       "20:00",
    luogo:     "Gromo (BG)",
    tipo:      "concerto",
    locandina: "",
    nota:      "" },

  { titolo:    "Sushi Pradalunga",
    data:      "2026-07-25",
    ora:       "",
    luogo:     "Pradalunga (BG)",
    tipo:      "sushi",
    locandina: "sushi.jpg",
    nota:      "" },

  { titolo:    "Lydian 'Queen at Wembley' Tribute",
    data:      "2026-07-28",
    ora:       "",
    luogo:     "Gazzaniga (BG)",
    tipo:      "lydian",
    locandina: "lydian.jpeg",
    nota:      "" },

  { titolo:    "Sushi Cornucopia",
    data:      "2026-08-06",
    ora:       "",
    luogo:     "Rovetta (BG)",
    tipo:      "sushi",
    locandina: "sushi.jpg",
    nota:      "" },

  { titolo:    "Presentatore Concerto bandistico",
    data:      "2026-08-07",
    ora:       "20:00",
    luogo:     "Gromo (BG)",
    tipo:      "concerto",
    locandina: "",
    nota:      "" },

  { titolo:    "Presentatore Concerto bandistico",
    data:      "2026-08-09",
    ora:       "20:00",
    luogo:     "Gromo (BG)",
    tipo:      "concerto",
    locandina: "",
    nota:      "" },

  { titolo:    "Sushi Cornucopia",
    data:      "2026-08-25",
    ora:       "21:30",
    luogo:     "Castione della Presolana (BG)",
    tipo:      "sushi",
    locandina: "sushi.jpg",
    nota:      "" },

  { titolo:    "'Là, dove nasce l'acqua'",
    data:      "2026-08-29",
    ora:       "16:00",
    luogo:     "Ponte Nossa (BG)",
    tipo:      "teatro",
    locandina: "acqua.webp",
    nota:      "" },

  { titolo:    "Sushi Pradalunga",
    data:      "2026-09-04",
    ora:       "",
    luogo:     "Pradalunga (BG)",
    tipo:      "sushi",
    locandina: "sushi.jpg",
    nota:      "" },

  { titolo:    "Parabole di un clown",
    data:      "2026-09-26",
    ora:       "",
    luogo:     "Bologna",
    tipo:      "teatro",
    locandina: "parabole.jpg",
    nota:      "" },

];
